#konfigurasi
server:
  port: 9999
spring:
  application:
    name: online-banking-example
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_banking
    username: root
    password: root
---
spring:
  jpa:
    hibernate:
      ddl-auto: validate
---
spring:
  jpa:
    show-sql: true