#konfigurasi inventory
server:
   port: ${PORT:8882}
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/db_demo_inventory?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: root
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: validate   