#konfigurasi product
server:
   port: ${PORT:8881}
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/db_demo_product?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: root
   jpa:
      hibernate:
         ddl-auto: validate
      show-sql: true   