//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.02 at 10:27:44 PM WIB 
//


package com.myhost.soap_jpa.person_ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.myhost.soap_jpa.person_ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.myhost.soap_jpa.person_ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetResponsePersonAll }
     * 
     */
    public GetResponsePersonAll createGetResponsePersonAll() {
        return new GetResponsePersonAll();
    }

    /**
     * Create an instance of {@link PersonInfo }
     * 
     */
    public PersonInfo createPersonInfo() {
        return new PersonInfo();
    }

    /**
     * Create an instance of {@link AddRequestPerson }
     * 
     */
    public AddRequestPerson createAddRequestPerson() {
        return new AddRequestPerson();
    }

    /**
     * Create an instance of {@link GetResponsePersonById }
     * 
     */
    public GetResponsePersonById createGetResponsePersonById() {
        return new GetResponsePersonById();
    }

    /**
     * Create an instance of {@link DeleteResponsePerson }
     * 
     */
    public DeleteResponsePerson createDeleteResponsePerson() {
        return new DeleteResponsePerson();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link UpdateRequestPerson }
     * 
     */
    public UpdateRequestPerson createUpdateRequestPerson() {
        return new UpdateRequestPerson();
    }

    /**
     * Create an instance of {@link GetRequestPersonById }
     * 
     */
    public GetRequestPersonById createGetRequestPersonById() {
        return new GetRequestPersonById();
    }

    /**
     * Create an instance of {@link DeleteRequestPerson }
     * 
     */
    public DeleteRequestPerson createDeleteRequestPerson() {
        return new DeleteRequestPerson();
    }

    /**
     * Create an instance of {@link AddResponsePerson }
     * 
     */
    public AddResponsePerson createAddResponsePerson() {
        return new AddResponsePerson();
    }

    /**
     * Create an instance of {@link UpdateResponsePerson }
     * 
     */
    public UpdateResponsePerson createUpdateResponsePerson() {
        return new UpdateResponsePerson();
    }

    /**
     * Create an instance of {@link GetRequestPersonAll }
     * 
     */
    public GetRequestPersonAll createGetRequestPersonAll() {
        return new GetRequestPersonAll();
    }

}
