#konfigurasi service registry
server:
  port: 8761
spring:
  application:
    name: spring-cloud-load-balancing-eureka
eureka:
  instance:
    client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    leaseRenewalIntervalInSeconds: 3
    prefereIpAddress: true