#server.port=8881
#spring.application.name=spring-cloud-load-balancing-web

server:
  port: 8881
spring:
  application:
    name: spring-cloud-load-balancing-web
eureka:
  instance:
    appname: spring-cloud-load-balancing-web
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/