CREATE TABLE OAUTH_CLIENT_DETAILS (
CLIENT_ID VARCHAR(255) NOT NULL PRIMARY KEY,
CLIENT_SECRET VARCHAR(255) NOT NULL,
RESOURCE_IDS VARCHAR(255) DEFAULT NULL,
SCOPE VARCHAR(255) DEFAULT NULL,
AUTHORIZED_GRANT_TYPES VARCHAR(255) DEFAULT NULL,
WEB_SERVER_REDIRECT_URI VARCHAR(255) DEFAULT NULL,
AUTHORITIES VARCHAR(255) DEFAULT NULL,
ACCESS_TOKEN_VALIDITY INT(11) DEFAULT NULL,
REFRESH_TOKEN_VALIDITY INT(11) DEFAULT NULL,
ADDITIONAL_INFORMATION VARCHAR(4096) DEFAULT NULL,
AUTOAPPROVE VARCHAR(255) DEFAULT NULL);
 
 INSERT INTO OAUTH_CLIENT_DETAILS (
	CLIENT_ID,CLIENT_SECRET,
	RESOURCE_IDS,
	SCOPE,
	AUTHORIZED_GRANT_TYPES,
	WEB_SERVER_REDIRECT_URI,AUTHORITIES,
	ACCESS_TOKEN_VALIDITY,REFRESH_TOKEN_VALIDITY,
	ADDITIONAL_INFORMATION,AUTOAPPROVE)
	VALUES(
    'USER_CLIENT_APP','{bcrypt}$2a$10$EOs8VROb14e7ZnydvXECA.4LoIhPOoFHKvVF/iBZ/ker17Eocz4Vi',
	'USER_CLIENT_RESOURCE,USER_ADMIN_RESOURCE',
	'role_admin,role_user',
	'authorization_code,password,refresh_token,implicit',
	NULL,NULL,
	900,3600,
	'{}',NULL);
 
 
 
CREATE TABLE PERMISSIONS (
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(60) UNIQUE KEY);

INSERT INTO PERMISSIONS (NAME) VALUES 
('can_create_user'),
('can_update_user'),
('can_read_user'),
('can_delete_user');



		CREATE TABLE ROLES 
		(ID INT PRIMARY KEY AUTO_INCREMENT, 
		NAME VARCHAR(60) UNIQUE KEY);


		INSERT INTO ROLES (NAME) VALUES 
		('role_admin'),('role_user');


		

	CREATE TABLE PERMISSIONS_ROLES(
    PERMISSIONS_ID INT,
    FOREIGN KEY(PERMISSIONS_ID) REFERENCES PERMISSIONS(ID),
    ROLES_ID INT,
    FOREIGN KEY(ROLES_ID) REFERENCES ROLES(ID));
    
    INSERT INTO PERMISSIONS_ROLES (PERMISSIONS_ID, ROLES_ID) VALUES 
    (1,1), /* can_create_user assigned to role_admin */
    (2,1), /* can_update_user assigned to role_admin */
    (3,1), /* can_read_user assigned to role_admin */
    (4,1), /* can_delete_user assigned to role_admin */

    (3,2);  /* can_read_user assigned to role_user */
    


    

	CREATE TABLE USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(24) UNIQUE KEY NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    ENABLED BIT(1) NOT NULL,
    ACCOUNT_EXPIRED BIT(1) NOT NULL,
    CREDENTIALS_EXPIRED BIT(1) NOT NULL,
    ACCOUNT_LOCKED BIT(1) NOT NULL);
    
    
    


	INSERT INTO USERS (
    USERNAME,PASSWORD,
    EMAIL,ENABLED,ACCOUNT_EXPIRED,CREDENTIALS_EXPIRED,ACCOUNT_LOCKED) VALUES (
    'admin','{bcrypt}$2a$10$EOs8VROb14e7ZnydvXECA.4LoIhPOoFHKvVF/iBZ/ker17Eocz4Vi',
    'william@gmail.com',1,0,0,0),
    ('user','{bcrypt}$2a$10$EOs8VROb14e7ZnydvXECA.4LoIhPOoFHKvVF/iBZ/ker17Eocz4Vi',
    'john@gmail.com',1,0,0,0);
    
    
    
	CREATE TABLE ROLES_USERS (ROLES_ID INT,FOREIGN KEY(ROLES_ID) REFERENCES ROLES(ID),
    USERS_ID INT, FOREIGN KEY(USERS_ID) REFERENCES USERS(ID));
    
    
    INSERT INTO ROLES_USERS (ROLES_ID, USERS_ID)
    VALUES 
    (1, 1) /* role_admin assigned to admin user */,
(2, 2) /* role_user assigned to user user */ ;


CREATE TABLE VERIFY_TOKEN(
	ID INT AUTO_INCREMENT,
	TOKEN VARCHAR(255),
	STATUS VARCHAR(255),
	EXPIRED_TOKEN DATETIME,
	ISSUE_TOKEN DATETIME,
	CONFIRM_TOKEN DATETIME,
	USERS_ID INT UNIQUE,
	
	CONSTRAINT PK_VERIFY_TOKEN_ID PRIMARY KEY(ID),
	CONSTRAINT FK_VERIFY_TOKEN_USERS_ID FOREIGN KEY (USERS_ID) REFERENCES USERS(ID)
);