#konfigurasi auth-cloud-oauth2-resource
server:
   port: 9002
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/db_auth_cloud
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
---
spring:
   jpa:
      hibernate:
         ddl-auto: validate
      show:
         sql: true
#konfigurasi security

