#konfigurasi load balancing
spring:
  application:
    name: spring-cloud-load-balancing-app
server:
  port: 8777

#ping-server:
#  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: localhost:10000,localhost:9999,localhost:9998
#    ServerListRefreshInterval: 2000

spring-cloud-load-balancing-web:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:10000,localhost:9999,localhost:9998
    ServerListRefreshInterval: 2000

eureka:
  instance:
    appname: spring-cloud-load-balancing-app
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/